const data = [
  {
    bullet: "Z",
    name: "Zeus",
    nameKo: "(최우제)",
    speaking: `"오늘까지만 세계 최고의 탑을 하고 내일부터 다시 도전자의 마음으로 돌아가겠다"`,
    speakingSource: "- Worlds 2023 우승 인터뷰 -",
    birthday: "2004.01.31",
    team: "T1",
    lane: "Top",
    debut: "2021.02.03",
    shortsURL: "https://youtube.com/shorts/J-PSr5bXfZY?si=Kes2HxzM3d_92TDb",
    instagramURL: "https://www.instagram.com/godthunderzeus/",
  },
  {
    bullet: "O",
    name: "Oner",
    nameKo: "(문현준)",
    speaking: `"가장 예쁜 꽃은 우여곡절 끝에 피는 꽃.
    오늘은 제일 예쁜 꽃이 핀 것 같아서 기분 좋다."`,
    speakingSource: "- Worlds 2023 우승 인터뷰 -",
    birthday: "2002.12.24",
    team: "T1",
    lane: "Jungle",
    debut: "2021.02.21",
    shortsURL: "https://youtube.com/shorts/3lNpOEbCJy4?si=hnyD9_EAquh2-YAq",
    instagramURL: "https://www.instagram.com/t1_oner/",
  },
  {
    bullet: "F",
    name: "Faker",
    nameKo: "(이상혁)",
    speaking: `"세 번째 우승은 저를 위한 것이었습니다.
    네 번째 우승은 우리 팀을 위한 것입니다."`,
    speakingSource: "- Worlds 2023 결승 티저 - ",
    birthday: "1996.05.07",
    team: "T1",
    lane: "Middle",
    debut: "2013.04.06",
    shortsURL: "https://youtube.com/shorts/HDfZBguBvnI?si=mcWMyotb3BaRnIvK",
    instagramURL: "https://www.instagram.com/faker/",
  },
  {
    bullet: "G",
    name: "Gumayusi",
    nameKo: "(이민형)",
    speaking: `"최고의 선수가 있을 곳은 T1이니까"`,
    speakingSource: "- 2020.11.24 T1 재계약 후 SNS -",
    birthday: "2002.02.06",
    team: "T1",
    lane: "Bottom",
    debut: "2020.09.08",
    shortsURL: "https://youtube.com/shorts/-FnLCajGxHw?si=9zNoZUMbLEwao3Wi",
    instagramURL: "https://www.instagram.com/t1_gumayusi/",
  },
  {
    bullet: "K",
    name: "Keria",
    nameKo: "(류민석)",
    speaking: `"케리아 저 선수는 진짜 역대급 천재 괴물인 것 같아요."`,
    speakingSource: "- 2020 LCK 스프링 2주차 AF vs DRX전 해설가 클템 -",
    birthday: "2002.10.14",
    team: "T1",
    lane: "Support",
    debut: "2019.12.26",
    shortsURL: "https://youtube.com/shorts/qZLIEyhnAvE?si=srVKOhNJA-nei9aZ",
    instagramURL: "https://www.instagram.com/keria_minseok/",
  },
];
